### ŞUBİLET API Test Dosyası
### VS Code'da REST Client eklentisi ile kullanabilirsiniz

### Değişkenler
@baseUrl = http://localhost:8080/api

###############################################
### AIRPORTS - Havalimanları
###############################################

### Tüm havalimanlarını listele
GET {{baseUrl}}/airports

### ID ile havalimanı getir
GET {{baseUrl}}/airports/1

### Koda göre havalimanı getir (IST)
GET {{baseUrl}}/airports/code/IST

###############################################
### AIRLINES - Havayolları
###############################################

### Tüm havayollarını listele
GET {{baseUrl}}/airlines

### ID ile havayolu getir
GET {{baseUrl}}/airlines/1

###############################################
### FLIGHTS - Uçuşlar
###############################################

### Tüm uçuşları listele
GET {{baseUrl}}/flights

### ID ile uçuş getir
GET {{baseUrl}}/flights/1

### Uçuş ara (İstanbul -> Ankara, 1 Aralık 2025)
GET {{baseUrl}}/flights/search?originAirportId=1&destinationAirportId=3&date=2025-12-01

### Uçuş ara (İstanbul -> Antalya)
GET {{baseUrl}}/flights/search?originAirportId=1&destinationAirportId=4&date=2025-12-01

### Uçuş ara (İstanbul -> İzmir)
GET {{baseUrl}}/flights/search?originAirportId=1&destinationAirportId=5&date=2025-12-01

###############################################
### CUSTOMERS - Müşteriler
###############################################

### Tüm müşterileri listele
GET {{baseUrl}}/customers

### ID ile müşteri getir
GET {{baseUrl}}/customers/1

### TC No ile müşteri getir
GET {{baseUrl}}/customers/tc/12345678901

### Yeni müşteri ekle
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "tcNo": "98765432101",
  "isimSoyad": "Test Kullanıcı",
  "dogumTarihi": "1995-01-15",
  "uyruk": "Türkiye",
  "cinsiyet": "Erkek",
  "mail": "test@example.com",
  "telNo": "05551234567"
}

###############################################
### RESERVATIONS - Rezervasyonlar
###############################################

### Tüm rezervasyonları listele
GET {{baseUrl}}/reservations

### ID ile rezervasyon getir
GET {{baseUrl}}/reservations/1

### PNR ile rezervasyon getir
GET {{baseUrl}}/reservations/pnr/PNRABC123

### Müşteriye göre rezervasyonları getir
GET {{baseUrl}}/reservations/customer/1

### Yeni rezervasyon oluştur
POST {{baseUrl}}/reservations
Content-Type: application/json

{
  "customer": {
    "userId": 1
  },
  "flight": {
    "flightId": 1
  },
  "seatNumber": "25C"
}

### Rezervasyon iptal et
PUT {{baseUrl}}/reservations/1/cancel

###############################################
### PAYMENTS - Ödemeler
###############################################

### Tüm ödemeleri listele
GET {{baseUrl}}/payments

### ID ile ödeme getir
GET {{baseUrl}}/payments/1

### Rezervasyona göre ödeme getir
GET {{baseUrl}}/payments/reservation/1

### Yeni ödeme oluştur
POST {{baseUrl}}/payments
Content-Type: application/json

{
  "reservation": {
    "reservationId": 1
  },
  "method": "Credit Card",
  "currency": "TRY",
  "amount": 850.00
}

###############################################
### ADMIN - Yönetici
###############################################

### Admin girişi
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Yeni admin kaydı
POST {{baseUrl}}/admin/register
Content-Type: application/json

{
  "username": "testadmin",
  "password": "test123",
  "fullName": "Test Admin"
}

###############################################
### AIRCRAFTS - Uçaklar
###############################################

### Tüm uçakları listele
GET {{baseUrl}}/aircrafts

### ID ile uçak getir
GET {{baseUrl}}/aircrafts/1

### Havayoluna göre uçakları getir
GET {{baseUrl}}/aircrafts/airline/1



